<header class="page-heading">
    <div><span class="eyebrow">Your market routine, your way.</span><h1>One calm place for every preference.</h1><p>Personalize the paper account, charts, Telegram routine, alerts, and AI estimates. Server keys stay only in <code>.env</code> or n8n credentials.</p></div>
    <div class="setup-health"><span class="status-dot <?= $marketConfigured?'ok':'warning' ?>"></span><div><strong><?= $marketConfigured?'Market provider configured':'Market key required' ?></strong><small><?= $marketConfigured?'Run the live test before presenting.':'Add MARKET_DATA_API_KEY to .env.' ?></small></div></div>
</header>

<nav class="setup-nav" aria-label="Setup sections"><a href="#profile">Profile</a><a href="#paper-account">Paper account</a><a href="#dashboard-settings">Dashboard</a><a href="#ai-settings">AI estimates</a><a href="#telegram">Telegram</a><a href="#alerts">Alerts</a><a href="#automation">Automation</a></nav>

<section class="settings-section panel" id="profile">
    <div class="settings-copy"><span class="eyebrow">01 · Profile</span><h2>Your personal account</h2><p>Update the name shown throughout the site and the timezone used for your daily reports and quiet hours.</p><div class="setting-stat"><span>Signed-in email</span><strong><?= e($settings['email'] ?? '') ?></strong><small>Account role: <?= e(ucfirst((string) ($settings['role'] ?? 'trader'))) ?></small></div></div>
    <form class="settings-form api-form" data-endpoint="/api/settings/profile" data-method="PATCH">
        <label>Display name<input type="text" name="name" maxlength="100" required value="<?= e($settings['name'] ?? '') ?>"></label>
        <label>Timezone<input type="text" name="timezone" list="profile-timezones" required value="<?= e($settings['timezone'] ?? config('app.timezone', 'Europe/Brussels')) ?>"><datalist id="profile-timezones"><?php foreach (timezone_identifiers_list() as $timezone): ?><option value="<?= e($timezone) ?>"><?php endforeach; ?></datalist></label>
        <button class="button primary" type="submit">Save profile</button>
    </form>
</section>

<section class="settings-section panel" id="paper-account">
    <div class="settings-copy"><span class="eyebrow">02 · Paper account</span><h2>Virtual balance & trading rules</h2><p>These controls affect simulated trades only. Changing the display settings never moves real money.</p><div class="setting-stat"><span>Current virtual cash</span><strong><?= e(money((float)($settings['current_cash']??0),(string)($settings['base_currency']??'USD'))) ?></strong><small>Starting balance <?= e(money((float)($settings['starting_cash']??0),(string)($settings['base_currency']??'USD'))) ?></small></div></div>
    <form class="settings-form api-form" data-endpoint="/api/settings/paper-account" data-method="PATCH">
        <div class="form-grid"><label>Base currency<select name="base_currency"><option value="USD" <?= ($settings['base_currency']??'USD')==='USD'?'selected':'' ?>>USD</option><option value="EUR" <?= ($settings['base_currency']??'')==='EUR'?'selected':'' ?>>EUR</option></select></label><label>Default simulated fee<input type="number" name="default_fee" min="0" step="0.01" value="<?= e($settings['default_fee']??0) ?>"></label></div>
        <label class="check-row"><input type="checkbox" name="allow_fractional_shares" value="1" <?= !empty($settings['allow_fractional_shares'])?'checked':'' ?>> Allow fractional shares (up to eight decimals)</label>
        <div class="form-grid"><label class="check-card"><input type="checkbox" name="morning_report_enabled" value="1" <?= !empty($settings['morning_report_enabled'])?'checked':'' ?>><span><strong>Daily morning report</strong><small>The Telegram bot sends this once each day at your chosen local time.</small></span></label><label>Daily delivery time<input type="time" name="morning_report_time" value="<?= e(substr((string)($settings['morning_report_time']??'07:30'),0,5)) ?>"></label></div>
        <label class="check-row"><input type="checkbox" name="market_close_report_enabled" value="1" <?= !empty($settings['market_close_report_enabled'])?'checked':'' ?>> Send one Telegram report after the regular US market close (4:00 PM New York time, weekdays)</label>
        <div class="form-grid"><label class="check-card"><input type="checkbox" name="quiet_hours_enabled" value="1" <?= !empty($settings['quiet_hours_enabled'])?'checked':'' ?>><span><strong>Quiet hours</strong><small>Suppress normal alerts across the selected period.</small></span></label><label>Start<input type="time" name="quiet_hours_start" value="<?= e(substr((string)($settings['quiet_hours_start']??''),0,5)) ?>"></label><label>End<input type="time" name="quiet_hours_end" value="<?= e(substr((string)($settings['quiet_hours_end']??''),0,5)) ?>"></label></div>
        <div class="form-actions"><button class="button primary" type="submit">Save paper settings</button><button class="button danger" type="button" id="open-reset">Reset my paper portfolio</button></div>
    </form>
</section>

<section class="settings-section panel" id="dashboard-settings">
    <div class="settings-copy"><span class="eyebrow">03 · Dashboard</span><h2>Graphs & important stocks</h2><p>Choose the two chart summaries shown on Dashboard. Stock price options need a selected stock.</p></div>
    <form class="settings-form api-form" data-endpoint="/api/settings/dashboard" data-method="PATCH">
        <div class="form-grid"><label>Graph 1 type<select name="primary_chart_type"><option value="portfolio_value" <?= ($settings['primary_chart_type']??'')==='portfolio_value'?'selected':'' ?>>Portfolio value</option><option value="profit_loss" <?= ($settings['primary_chart_type']??'')==='profit_loss'?'selected':'' ?>>Profit / loss</option><option value="stock_price" <?= ($settings['primary_chart_type']??'')==='stock_price'?'selected':'' ?>>Selected stock price</option></select></label><label>Graph 1 stock<select name="primary_chart_stock_id"><option value="">None</option><?php foreach($dashboardStocks as $stock):?><option value="<?= (int)$stock['id'] ?>" <?= (int)($settings['primary_chart_stock_id']??0)===(int)$stock['id']?'selected':'' ?>><?= e($stock['symbol'].' · '.$stock['company_name']) ?></option><?php endforeach;?></select></label></div>
        <div class="form-grid"><label>Graph 2 type<select name="secondary_chart_type"><option value="portfolio_allocation" <?= ($settings['secondary_chart_type']??'')==='portfolio_allocation'?'selected':'' ?>>Portfolio allocation</option><option value="daily_performance" <?= ($settings['secondary_chart_type']??'')==='daily_performance'?'selected':'' ?>>Daily performance</option><option value="stock_price" <?= ($settings['secondary_chart_type']??'')==='stock_price'?'selected':'' ?>>Selected stock price</option></select></label><label>Graph 2 stock<select name="secondary_chart_stock_id"><option value="">None</option><?php foreach($dashboardStocks as $stock):?><option value="<?= (int)$stock['id'] ?>" <?= (int)($settings['secondary_chart_stock_id']??0)===(int)$stock['id']?'selected':'' ?>><?= e($stock['symbol'].' · '.$stock['company_name']) ?></option><?php endforeach;?></select></label></div>
        <fieldset><legend>Important owned/watchlist stocks</legend><div class="stock-checkboxes"><?php foreach($dashboardStocks as $stock):?><label><input type="checkbox" name="important_stock_ids[]" value="<?= (int)$stock['id'] ?>" <?= in_array((int)$stock['id'],array_map('intval',$settings['important_stock_ids']??[]),true)?'checked':'' ?>><span><strong><?= e($stock['symbol']) ?></strong><small><?= e($stock['company_name']) ?></small></span></label><?php endforeach;?></div></fieldset>
        <label>Maximum important-stock cards<input type="number" name="max_important_stocks" min="1" max="8" value="<?= e($settings['max_important_stocks']??4) ?>"></label><button class="button primary" type="submit">Save dashboard</button>
    </form>
</section>

<section class="settings-section panel" id="ai-settings">
    <div class="settings-copy"><span class="eyebrow">04 · Alert predictions</span><h2>Prediction included with each triggered alert</h2><p>When one of your configured stock rules is triggered, the bot creates a fresh estimate and includes its signal, probability, confidence, risk, and explanation in the same Telegram message.</p><div class="notice info">OpenRouter key and global API credentials are edited only in server-side <code>.env</code>.</div></div>
    <form class="settings-form api-form" data-endpoint="/api/settings/ai" data-method="PATCH">
        <label>Allowed OpenRouter model<input type="text" name="ai_model" value="<?= e($settings['ai_model']??'nvidia/nemotron-3-super-120b-a12b:free') ?>" required></label>
        <input type="hidden" name="prediction_refresh_hours" value="<?= e($settings['prediction_refresh_hours']??6) ?>">
        <label>Prediction horizon included in alerts<select name="default_horizon"><option value="1d" <?= ($settings['default_horizon']??'')==='1d'?'selected':'' ?>>Next trading day (1d)</option><option value="7d" <?= ($settings['default_horizon']??'7d')==='7d'?'selected':'' ?>>Next 7 calendar days (7d)</option><option value="30d" <?= ($settings['default_horizon']??'')==='30d'?'selected':'' ?>>Next 30 calendar days (30d)</option></select></label>
        <div class="form-grid"><label>Urgent confidence minimum (%)<input type="number" name="minimum_urgent_confidence" min="0" max="100" step="0.1" value="<?= e($settings['minimum_urgent_confidence']??70) ?>"></label><label>Maximum news items<input type="number" name="max_news_items" min="0" max="20" value="<?= e($settings['max_news_items']??5) ?>"></label></div>
        <label class="check-row"><input type="checkbox" name="news_analysis_enabled" value="1" <?= !empty($settings['news_analysis_enabled'])?'checked':'' ?>> Enable news context when available</label><button class="button primary" type="submit">Save AI preferences</button>
    </form>
</section>

<section class="settings-section panel" id="telegram">
    <div class="settings-copy"><span class="eyebrow">05 · Telegram</span><h2>One bot for notifications and stock questions</h2><p>The local Telegram Hub sends alerts and reports, then accepts tickers or company names such as <code>/stock NVDA</code>, <code>/stock NVIDIA</code>, <code>Apple</code>, <code>what about Tesla?</code>, or <code>what's new with NVIDIA?</code>. Explicit <code>/stock</code> requests use the immediate factual path. Natural questions use the AI chat path with the same live quote context and automatically fall back to the factual answer if AI is unavailable.</p><div class="notice info">Telegram is polled once per minute, so a normal reply should arrive within about 60 seconds while both WAMP and Docker Desktop are running.</div><div class="verification <?= !empty($settings['telegram_verified'])?'verified':'unverified' ?>"><span><?= !empty($settings['telegram_verified'])?'✓':'!' ?></span><div><strong><?= !empty($settings['telegram_verified'])?'Connection verified':'Not verified' ?></strong><small>Last test <?= e($settings['last_test_at']??'never') ?> · <?= e($settings['last_test_status']??'not run') ?></small></div></div></div>
    <form class="settings-form" id="telegram-form"><label>Telegram chat ID<input type="text" name="chat_id" value="<?= e($settings['chat_id']??'') ?>" placeholder="Example: 123456789" required></label><label>Telegram username (optional)<input type="text" name="telegram_username" value="<?= e($settings['telegram_username']??'') ?>" placeholder="@username"></label><label class="check-row"><input type="checkbox" name="is_enabled" value="1" <?= !isset($settings['telegram_enabled'])||!empty($settings['telegram_enabled'])?'checked':'' ?>> Enable Telegram delivery</label><div class="form-actions"><button class="button secondary" type="submit" data-mode="save">Save connection</button><button class="button primary" type="button" id="test-telegram">Send test message</button></div></form>
</section>

<section class="settings-section panel" id="alerts">
    <div class="settings-copy"><span class="eyebrow">06 · Stocks to monitor</span><h2>Choose when the Telegram bot should notify you</h2><p>Only stocks with enabled rules below are monitored. When a threshold is crossed, one Telegram message contains the price change and a fresh prediction.</p><div class="unit-callout"><strong>Percentage interpretation</strong><span><code>0.2</code> means exactly <code>0.2%</code> when Percentage is selected.</span></div></div>
    <div class="settings-form">
        <form id="alert-form" class="stack-form"><input type="hidden" name="is_enabled" value="1"><input type="hidden" name="ai_commentary_enabled" value="1"><label>Stock<select name="stock_id" required><option value="">Select a stock</option><?php foreach($stocks as $stock):?><option value="<?= (int)$stock['id'] ?>"><?= e($stock['symbol'].' · '.$stock['company_name']) ?></option><?php endforeach;?></select></label><label>Alert name<input type="text" name="name" maxlength="120" placeholder="AAPL 0.2% move" required></label><div class="form-grid"><label>Threshold type<select name="threshold_type" id="threshold-type"><option value="percent">Percentage change</option><option value="absolute_price">Absolute price movement</option><option value="target_price">Target price</option></select></label><label>Threshold <span id="threshold-unit">%</span><input type="number" name="threshold_value" min="0.00000001" step="0.00000001" value="0.2" required></label></div><div class="form-grid"><label>Direction<select name="direction"><option value="both">Both</option><option value="increase">Increase</option><option value="decrease">Decrease</option></select></label><label>Reference<select name="reference_type"><option value="previous_close">Previous close</option><option value="last_alert_price">Last alert price</option><option value="average_cost">Average purchase price</option><option value="fixed_price">Fixed reference price</option></select></label></div><label>Fixed reference price (only when selected)<input type="number" name="reference_price" min="0" step="0.00000001"></label><div class="form-grid"><label>Check interval<select name="check_interval_minutes"><option value="5">5 minutes</option><option value="15">15 minutes</option><option value="30">30 minutes</option><option value="60">60 minutes</option></select></label><label>Cooldown (minutes)<input type="number" name="cooldown_minutes" min="1" max="1440" value="30"></label><label>Minimum confidence (%)<input type="number" name="minimum_confidence" min="0" max="100" value="0"></label></div><label class="check-row"><input type="checkbox" name="market_hours_only" value="1" checked> Market hours only</label><div class="notice info">A fresh prediction is always included when this alert triggers.</div><button class="button primary" type="submit">Create alert rule</button></form>
        <div class="alert-list" id="alert-list"><h3>Existing rules</h3><?php if($alerts):foreach($alerts as $alert):?><article><div><strong><?= e($alert['name']) ?></strong><span><?= e($alert['symbol']) ?> · <?= e($alert['threshold_value']) ?><?= $alert['threshold_type']==='percent'?'%':' '.$alert['threshold_type'] ?> · <?= e($alert['direction']) ?></span><small><?= !empty($alert['is_enabled'])?'Enabled':'Paused' ?> · <?= (int)$alert['check_interval_minutes'] ?> min interval · <?= (int)$alert['cooldown_minutes'] ?> min cooldown</small></div><div><button class="button ghost" data-alert-action="test" data-alert-id="<?= (int)$alert['id'] ?>">Test</button><button class="button ghost" data-alert-action="toggle" data-alert-id="<?= (int)$alert['id'] ?>" data-alert='<?= e(json_encode($alert,JSON_HEX_APOS|JSON_HEX_QUOT)) ?>'><?= !empty($alert['is_enabled'])?'Pause':'Enable' ?></button><button class="button danger" data-alert-action="delete" data-alert-id="<?= (int)$alert['id'] ?>">Delete</button></div></article><?php endforeach;else:?><p class="muted">No alert rules created.</p><?php endif;?></div>
    </div>
</section>

<section class="settings-section panel" id="automation">
    <div class="settings-copy"><span class="eyebrow">07 · n8n status</span><h2>One Telegram Hub</h2><p><strong>STOCK AI – Telegram Hub</strong> is the only active workflow. It checks configured stock alerts every five minutes, due morning reports each minute, market close at 4:00 PM New York on weekdays, and incoming Telegram questions by local polling.</p><?php if(is_admin()):?><div class="form-actions"><button class="button danger" data-automation="pause">Pause all</button><button class="button secondary" data-automation="resume">Resume all</button></div><?php endif;?></div>
    <div class="settings-form"><div class="automation-status-grid"><div><span>n8n base URL</span><strong><?= e(\App\Config\Env::get('N8N_BASE_URL','Not configured')) ?></strong></div><div><span>Internal key</span><strong><?= \App\Config\Env::get('INTERNAL_N8N_API_KEY')==='replace-with-a-long-random-value'?'Replace placeholder':'Configured' ?></strong></div><div><span>Server flag</span><strong><?= \App\Config\Env::bool('AUTOMATIONS_ENABLED',true)?'Enabled':'Disabled' ?></strong></div></div><?php if(is_admin()):?><div class="table-scroll"><table><thead><tr><th>Workflow</th><th>Status</th><th>Message</th><th>Started</th></tr></thead><tbody><?php foreach($automationLogs as $log):?><tr><td><?= e($log['workflow_name']) ?></td><td><span class="signal <?= e($log['status']) ?>"><?= e(strtoupper($log['status'])) ?></span></td><td><?= e($log['message']??'—') ?></td><td><?= e($log['started_at']) ?></td></tr><?php endforeach;?></tbody></table></div><?php else:?><p class="muted">Recent global automation logs are visible to Admin only.</p><?php endif;?></div>
</section>

<dialog id="reset-dialog" class="app-dialog"><form method="dialog" class="dialog-close-form"><button aria-label="Close">×</button></form><span class="eyebrow">Destructive paper-data action</span><h2>Reset your paper portfolio?</h2><p>This deletes your simulated transactions, holdings, position predictions, and alerts, then restores starting virtual cash. It never touches real money.</p><form id="reset-form" class="stack-form"><label>Re-enter your password<input type="password" name="password" required autocomplete="current-password"></label><label class="check-row"><input type="checkbox" name="confirm" value="1" required> I understand this cannot be undone.</label><button class="button danger full" type="submit">Reset paper portfolio</button></form></dialog>
